# Generated by Django 2.2.2 on 2019-06-17 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainfunction', '0002_projectdetails_constructer_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDetails',
            fields=[
                ('day', models.IntegerField(primary_key=True, serialize=False)),
                ('task_status', models.BinaryField()),
                ('reason', models.CharField(max_length=200)),
                ('project_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfunction.ProjectDetails')),
            ],
        ),
    ]
